version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/ebs
hooks:
  BeforeInstall:
    - location: deploy/before.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy/start.sh
      timeout: 300
      runas: root